eclipse-biscuit/biscuit-cli

Cargo.lock
src/main.rs

Example usage:
```
[geal@lolcatho biscuit-cli]$ cargo run -- inspect --raw-input - < ../spec/samples/v1/test10_authority_rules.bc
Finished dev [unoptimized + debuginfo] target(s) in 0.02s
Running `target/debug/biscuit inspect --raw-input -`
Authority block:
right(#authority, $1, #read) <- resource(#ambient, $1), owner(#ambient, $0, $1);
right(#authority, $1, #write) <- resource(#ambient, $1), owner(#ambient, $0, $1);
==========
Block n°1:
check if right(#authority, $0, $1), resource(#ambient, $0), operation(#ambient, $1);
check if resource(#ambient, $0), owner(#ambient, #alice, $0);
==========
```

use the block source code printer for inspection

---

Cargo.lock
Cargo.toml
src/main.rs

`biscuit generate`, `biscuit attenuate` (and `biscuit verify`, optionally),
read datalog provided by the user. In addition to inline datalog, and datalog read from
a user-provided file (or stdin, for `biscuit generate`), this commit adds the possibility
of reading datalog from a temporary file created by the CLI, with $EDITOR opened to edit it,
exactly like with `git commit`.
Error management is crude, and EDITOR is defaulted to `vim` if not present, but it works.
The temporary file is given a ~`.datalog`~ `.biscuit-datalog` extension so that editor has a chance to enable
language support (eg syntax coloring). ~I'm not super happy with the extension, as the
datalog used by biscuit is not standard (because of its extensions, and of the use of
`<-` instead of the more common `:-` sigil for …

Read datalog interactively with $EDITOR

---

Cargo.lock
Cargo.toml
src/main.rs

- prevent reading from stdin and $EDITOR at the same time
- be a bit nicer when interactively reading stuff from stdin

Improve tty things

---

src/main.rs

display more info when the authorizer check fails
The errors we are interested in are :
- failed datalog checks
- a deny policy matched
- no policy matched
- datalog computation was aborted (timeout, too many facts or iterations)
Note that the rust lib does not currently
- report when there are both failed checks and a deny policy matched. It seems that the failed checks take precedence;
- provide a pretty-printed version of the deny rule that matched (only its index)
```
biscuit inspect --raw-input ../biscuit/samples/v2/test13_block_rules.bc --public-key acdd6d5b53bfee478bf689f8e012fe7988bf755e3d7c5152947abc149bc20189 --verify-with 'time(2021-11-01T14:44:44Z); check if false; deny if true;'`
Authority block:
== Datalog ==
right("file1", "read");
right("file2", "read");
== Revocation id …
```

Datalog error output

---

Cargo.lock
Cargo.toml

A beta version has been released on crates.io

unpin git dep for biscuit-auth

---

Cargo.lock
Cargo.toml
src/main.rs

This fixes the broken `main` state, and uses the new error types
to improve error reporting:
- if there is a matched policy, it is displayed, in case of errors
or success
- failed checks are always displayed
Fixes #17 (and #16)

Bump biscuit-auth dependency

---

Cargo.lock
Cargo.toml
src/main.rs

Treat the $EDITOR environment variable as potentially having arguments, instead of just being a path to a binary.
This allows EDITOR="my-editor --some-param" without getting an error looking for a binary named "my-editor --some-param".
This commit brings in the [shell-words](https://crates.io/crates/shell-words) crate to parse out the editor arguments, which may or may not work well on Windows (the crate mentions parsing using unix rules). I looked at using `Exec::shell` from the [subprocess](https://crates.io/crates/subprocess) but this spawns a shell process and looked somewhat scarier.
Fixes #19.

Better handle $EDITOR with arguments

---

src/main.rs

This improves the UX a bit (a panic looks like an unexpected error, even though errors are properly handled throughout the program).
See #24
Before
```
❯ echo "user(1234);" | biscuit generate --private-key $(biscuit keypair --only-private-key) - | biscuit inspect --raw-input -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Format(DeserializationError("deserialization error: DecodeError { description: \"invalid wire type value: 7\", stack: [] }"))', src/main.rs:194:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After
```
❯ echo "user(1234);" | biscuit generate --private-key $(biscuit keypair --only-private-key) - | biscuit inspect --raw-input -
[Error] error deserializing or verifying the token
```

display error and exit(1) instead of panicking

---

Cargo.lock
Cargo.toml
src/cli.rs
src/input.rs
src/inspect.rs
src/main.rs

- generate third-party blocks (request / contents)
- display information about third-party blocks
```
biscuit generate-request test23_execution_scope.bc --raw-input > test-request
biscuit generate-third-party-block --private-key-file test-external-pk --block 'toto(1,2,3);' test-request > test-block-contents
biscuit append-third-party-block --block-contents-file test-block-contents test23_execution_scope.bc --raw-input
```
```
❯ biscuit append-third-party-block --block-contents-file test-block-contents ../biscuit-haskell/biscuit/test/samples/v2/test23_execution_scope.bc --raw-input | biscuit inspect -
Authority block:
== Datalog ==
authority_fact(1);
== Revocation id ==
6a3606836bc63b858f96ce5000c9bead8eda139ab54679a2a8d7a9984c2e5d864b93280acc1b728bed0be42b5b1c3be10f48a13a4dbd05fd5763de5be3 …
```

Support for third-party blocks

---

src/main.rs

Found these errors after updating and re-installing.
Maybe something has changed in biscuit-auth...
I suggest a humble fix.
```
error[E0308]: mismatched types
--> src/main.rs:70:23
|
70 |         KeyPair::from(private)
|         ------------- ^^^^^^^
|         |             |
|         |             expected `&PrivateKey`, found struct `PrivateKey`
|         |             help: consider borrowing here: `&private`
|         arguments to this function are incorrect
|
note: associated function defined here
--> /Users/allema_s/.cargo/git/checkouts/biscuit-rust-18543cf52e92de67/65e6f86/biscuit-auth/src/crypto/mod.rs:35:12
|
35 |     pub fn from(key: &PrivateKey) -> Self {
|            ^^^^
error[E0308]: `?` operator has incompatible types
--> src/main.rs:130:30
|
130 |     let root = …
```

Fix mismatched types errors after pull modifications

---

Cargo.lock
src/cli.rs
src/input.rs
src/inspect.rs
src/main.rs

Depends on https://github.com/biscuit-auth/biscuit-rust/pull/137
The `inspect-snapshot` command could be improved in the future with support for adding datalog code to the deserialized authorizer and maybe to query the fact base.
```
❯ biscuit inspect sample-biscuit --public-key 41e77e842e5c952a29233992dc8ebbedd2d83291a89bb0eec34457e723a69526 --verify-with 'ou($u, $o) <- op($o), user($u); op("op"); allow if user($u);' --dump-snapshot-to sample-snapshot
Authority block:
== Datalog ==
user("1234");
== Revocation id ==
a2532bf570cfed3e38aa0757c6dba67363f73bdde90876864ae054b37fdff27b1027b354e8f764ba3648312b73109dfa0839f16b04998d400aa133be6b57020d
==========
✅ Public key check succeeded 🔑
✅ Authorizer check succeeded 🛡️
Matched allow policy: allow if user($u)
❯ biscuit inspect-snapshot …
```

Support for saving and inspecting snapshots

---

CHANGELOG.md
src/cli.rs
src/inspect.rs
src/main.rs

It works okay, the only little issue is that `biscuit-rust` seems to report an incorrect error variant when trying to append a block to a sealed token: instead of `AppendOnSeal`, we get `AlreadySealed`.
Not a blocker, imo.

Sealing biscuits

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli.rs
src/inspect.rs
src/main.rs

```
biscuit-cli on  root-key-id [$?] is 📦 v0.3.0 via 🦀 v1.68.1
❯ echo 'toto(true)'|biscuit generate --private-key-file private.key --root-key-id 1 - | biscuit inspect -
Open biscuit
Authority block (root key identifier: 1):
== Datalog ==
toto(true);
== Revocation id ==
1d888c544b44172b8262328cb2b76fc6512143a0984bb0c25f289007cd7b4268990d99aedff3a2ca06c0025ed48574401d7eca8467ed354198bd452e020d7e0c
==========
🙈 Public key check skipped 🔑
🙈 Datalog check skipped 🛡️
```

generate: allow setting a root key id

---

build.rs
src/cli.rs

The syntax is now: `--param key:type=value`  (the previous syntax was `--param key=value::type`).
This improves the situation on many counts:
- the type annotation is on the name, not the value. This is more familiar for programming language users. The single colon makes it closer to rust (and idris, for that matter), but removes the nice haskell vibe.
- the type annotation is near the key, not the value, so a typo on the type annotation will likely end up in an error because of mismatching keys, insead of silently passing an unexpected term value
- the type annotation is checked against supported types instead of being silently ignored and passed as part of the value
Additionally, `bool` values are now supported, and `pubkey`/`bytes` literals are now consistent with the datalog syntax …

Improve parameter substitution syntax

---

src/cli.rs
src/errors.rs
src/inspect.rs
src/main.rs

This continues the extraction of common arguments, while adding support for running authorization on a snapshot.

Authorize snapshot

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli.rs
src/errors.rs
src/inspect.rs
src/main.rs

The `--json` flag on `biscuit inspect` now provides results in a structured JSON format:
```json
{
"token": {
"sealed": false,
"root_key_id": null,
"blocks": [
{
"code": "user(\"1234\");\n",
"external_key": null,
"revocation_id": "0ca759b390fbbb20461d9a2ca0b335371020262cbefc50854ee5cdc000339a877788f40baa0eb4af005eab0f26e556c0a86f063618d720c0619d7a67320de707"
},
{
"code": "user(\"4567\");\n",
"external_key": null,
"revocation_id": "c7e85b0c3bad81a1f381985042df1bd6b04f5c0029b0c38ec8565d767474953e9087af66ac396dd246f416038b7c02d2e943a1c5a5a4f282b7b3f4fcbc19fb0d"
}
]
},
"signatures_check": true,
"auth": {
"policies": [
"allow if user($u)"
],
"result": [
0,
"allow if user($u)"
]
},
"query": {
"query": "user($u) <- user($u)",
"query_all": true,
"facts": [
"user(\"1234\")",
"user(\"4567\")"
]
}
} …
```

Feat: JSON output in `biscuit inspect`

---

src/cli.rs
src/inspect.rs

Same as in #48, this allows passing a `--json` flag to `biscuit inspect-snapshot`.
```json
{
"snapshot": {
"code": "ou(\"1234\", \"op\");\nuser(\"1234\");\nop(\"op\");\nop(\"op\");\n\nou($u, $o) <- op($o), user($u);\n\nallow if user($u);\n",
"iterations": 1,
"elapsed_micros": 120
},
"auth": {
"policies": [
"allow if user($u)",
"allow if false"
],
"result": [
0,
"allow if user($u)"
]
},
"query": {
"query": "data($user) <- user($user)",
"query_all": false,
"facts": [
"data(\"1234\")"
]
}
}
```
`snapshot` is always returned: this is the snapshot contents: `code` contains all the code (more structured info might come later, such as token blocks, etc), while `iterations` and `elapsed_micros` give information about the time already spent computing, and the number of iterations needed to reach a …

feat: JSON output in biscuit inspect-snapshot

---

src/inspect.rs

This allows calling println only once

refactor: use Display instead of multiple println!s for inspection results

---

flake.lock
flake.nix

Add a Nix flake to biscuit-cli so it's easier to make use of `nix develop` and `nix shell` when playing with biscuits.
I tested that the `biscuit` program works when running `nix shell`. I tested that `cargo run`, `cargo test` (there are no tests?), `cargo fmt --check`, and `cargo clippy` all work in `nix develop`.
Really like the project and I find nix flakes make it easier to pull something down and play with it without doing too much installation.

Add Nix flake to biscuit-cli

---

Cargo.lock
src/inspect.rs

including `biscuit-auth` to `4.1.1`. This will fix an issue when displaying authorizer snapshots: all the facts and rules will be displayed, even when authorization has not been run yet.
Tested with `CgkI6AcQZBjAhD0QABpKCAQSAXgSAXkSBDEyMzQiDRADGgkKBwgKEgMYgggqGBADIhQKCAiACBIDCIAIEggIgQgSAwiACDoPCgIQABIJCgcIChIDGIIIQAA=`, the authorizer facts are correctly displayed even if they are not part of the datalog world yet.

chore: bump dependencies

---

src/inspect.rs

This makes it easy to see how much time evaluation took.
For `biscuit inspect`
```
✅ Public key check succeeded 🔑
❌ Authorizer check failed 🛡️ (139μs, 0 iterations)
No policy matched
```
For `biscuit inspect-snasphot`
```
⏱️ Execution time: 120μs (1 iterations)
✅ Authorizer check succeeded 🛡️ (148μs, 1 iterations)
Matched allow policy: allow if user($u)
```

Display evaluation time and iterations after authorization

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/cli.rs
src/errors.rs
src/input.rs
src/inspect.rs
src/main.rs

Prepping biscuit-cli for biscuit-auth 6.0.0
- biscuit-datalog v3.3 support
- ECDSA signatures support
- apply new snapshot limitations
`keypair` and all commands taking either a public or private key now take an extra `--key-algorithm` option (`ed25519` or `secp256r1`)
biscuit-rust does not allow modifying `Authorizer` contents anymore, so it is not possible to add authorizer contents to a snapshot after parsing it:
- `--authorize-with`, `--authorize-with-file`, `--authorize-interactive` have been removed from `inspect-snapshot`;
- evaluation and authz are always run in `inspect-snapshot`
when running queries, evaluation time after querying is now displayed

biscuit-auth 6.0.0

---

Cargo.lock
Cargo.toml
README.md
src/cli.rs
src/errors.rs
src/input.rs
src/inspect.rs
src/main.rs

biscuit-auth has optional support for the PEM format. biscuit-cli should expose that
- use an explicit option for key format instead of `--raw-xx` switches
- support for private key PEM input and output in `biscuit keypair`
- support for private key PEM input in `biscuit generate` and `biscuit generate-third-party-block`
- support for public key PEM input in `biscuit inspect`
- use `value_enum` for key format and key algorithm (automatic listing of possible values by clap)
- require and only accept `key-algorithm` when reading raw key bytes
- factor out common parameters for private key input in `generate` and `generate-third-party-block`
- support reading sepc256r1 keys in `--param`
<details>
<summary>Examples</summary>
```
❯ biscuit keypair --help
biscuit-keypair
Create and manipulate …
```

PEM support for key pairs
